In [2]:
import numpy as np

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
array = np.repeat(0.0, 10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array = np.repeat([1, 3], [2, 5])
array

array([1, 1, 3, 3, 3, 3, 3])

In [7]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
zeros = np.zeros([2, 5])
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
zeros.shape

(2, 5)

In [12]:
numbers = [[1, 2, 3], [3, 2, 1]]
numbers = np.array(numbers)

In [13]:
numbers[:, 1]

array([2, 2])